root: true
extends: airbnb
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: ignore
      exports: ignore
      functions: never
  function-paren-newline: off
  max-len: off
  no-console: off
  no-else-return: off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-unexpected-multiline: error
  prefer-destructuring: off
  semi:
    - error
    - never
plugins:
  - import
env:
  es6: true
  node: true
